### ISSUE TITLE
/src/main.cpp error

### ISSUE THREAD

**Issue by pyotam** [Phobos-Framework/phobos#2]
when running:
./build.sh

this is the error i get:
![image](https://cloud.githubusercontent.com/assets/15197376/18052772/ed63de3e-6e04-11e6-957c-6ab47bafe03a.png)

**Comment by emmericp** [comment]
should be fixed in 8cf8549

which OS and compiler are you using?

**Comment by pyotam** [comment]
Great, Thanks!
Ubuntu Server 14.04 and gcc.

**Comment by pyotam** [comment]
Hi,
I'm afraid the issue still exists...
by the way i'm running gcc 4.8.4 .
Yotam.

**Comment by emmericp** [comment]
i just tested it with ubuntu 14.04 and gcc 4.8.5 and it builds from a fresh clone.

since you are using phobos as a submodule in moongen: i just pushed the new submodule reference there, you probably didn't update the submodule.

**Comment by pyotam** [comment]
You were right,
It works fine now!
Thanks!
